meta_product_name: "Skuunaq Energy"
meta_title: "Skuunaq Energy - Paving the Way to a Hydrogen Economy"
meta_description: "Based in Northern Ireland, we strongly believe our project will act as the catalyst to decarbonise the energy industry. "
meta_image: "cover.png" # should exist in `app/assets/images/`
